name: Check Falabella Stock

on:
  schedule:
    - cron: '*/15 * * * *'  # cada 30 minutos
  workflow_dispatch:         # permite ejecutarlo manualmente desde el teléfono

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python check_stock.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SKU_ID: ${{ secrets.SKU_ID }}
